services:
  - name: web
    buildCommand: python manage.py collectstatic --noinput
    startCommand: gunicorn buskx.wsgi --bind 0.0.0.0:$PORT
    env:
      - key: SECRET_KEY
        from: env
      - key: DEBUG
        from: env
      - key: ALLOWED_HOSTS
        from: env
      - key: DB_NAME
        from: env
      - key: DB_USER
        from: env
      - key: DB_PASSWORD
        from: env
      - key: DB_HOST
        from: env
      - key: DB_PORT
        from: env

build:
  steps:
    - name: Install dependencies
      command: pip install -r requirements.txt
    - name: Run migrations
      command: python manage.py migrate
